theme: jekyll-theme-hacker
markdown: GFM
title: Arman Mazloumzadeh (@armanexplorer)
description: +5YRS in Backend Web Developer / Software Engineer with Python and Django
plugins:
  - jekyll-seo-tag

defaults:
  - 
    space:
      path: ""
    values:
      layout: "default"
      image: /assets/media/armanexplorer.png
  # -
  #   scope:
  #     path: "" # an empty string here means all files in the project
  #     type: "posts" # previously `post` in Jekyll 2.2.
  #   values:
  #     layout: "default"
