markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

title: Senior Software Engineer | Backend & DevOps Expert | Open to Relocation
description: 6+ years building scalable web platforms with Python, Django, and cloud technologies. Proven leadership in high-impact projects, ready for global opportunities.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

defaults:
  - 
    space:
      path: ""
    values:
      layout: "default"
      image: /assets/media/armanexplorer.png
  # -
  #   scope:
  #     path: "" # an empty string here means all files in the project
  #     type: "posts" # previously `post` in Jekyll 2.2.
  #   values:
  #     layout: "default"
