theme: jekyll-theme-hacker
markdown: GFM
title: armanexplorer planet
description: You can explore all about Software Engineering challagens in armanexplorer planet
plugins:
  - jekyll-seo-tag

defaults:
  - 
    space:
      path: ""
    values:
      layout: "default"
  # -
  #   scope:
  #     path: "" # an empty string here means all files in the project
  #     type: "posts" # previously `post` in Jekyll 2.2.
  #   values:
  #     layout: "default"
